substitutions:
  name: battery-monitor
  friendly_name: "FTV Battery Monitor"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

esphome:
  name: $name
  friendly_name: $friendly_name
  min_version: 2024.6.0
  name_add_mac_suffix: false

external_components:
  - source: github://SaschaKP/esphome-pace-bms@main
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:
  level: DEBUG

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

#api:
#  encryption:
#    key: !secret api
#  reboot_timeout: 20min

uart:
  - id: uart_1
    #default baud_rate is 9600 for PACE RS232, also the DEYE ESI WIFI MODULE use this RX and TX, on other modules this may vary
    baud_rate: 9600 
    tx_pin: GPIO17
    rx_pin: GPIO16
    rx_buffer_size: 3072 #to allow interrogation for all packs contemporarily (0xFF) in future development

pace_modbus:
  id: modbus0
  uart_id: uart_1
  rx_timeout: 500ms
  update_interval: 10s
  wait_network: false #this defaults to false, when true the loop to check and send data waits for network and api/mqtt to be online
  request_all_packs: false #this defaults to false, when true all packs will be asked at once, shortening the requests timing *experimental*

pace_bms:
  - id: bms1
    # Dip switch configuration of a multi pack setup / address 0x1
    #  8    7    6    5    4    3    2    1
    # off, off, off, off, off, off, off,  on
    address: 0x01
    protocol_version: 0x25
    pace_modbus_id: modbus0
  - id: bms2
    # Dip switch configuration of a multi pack setup / address 0x2
    #  8    7    6    5    4    3    2    1
    # off, off, off, off, off, off,  on, off
    address: 0x02
    protocol_version: 0x25
    pace_modbus_id: modbus0

sensor:
  - platform: wifi_signal
    name: "RSSI"
    id: sensor_rssi
    update_interval: 30s
    entity_category: "diagnostic"
  - platform: uptime
    name: "Uptime"
    id: sensor_uptime
    update_interval: 60s
    entity_category: "diagnostic"

packages:
  pack_1: !include
    file: pack.yaml
    vars:
      pace_bms_id: bms1
      pack: Bank 1
  pack_2: !include
    file: pack.yaml
    vars:
      pace_bms_id: bms2
      pack: Bank 2
